### ISSUE TITLE
[FR]: WebP options on exporting

### ISSUE THREAD

**Issue by RafaelLinux** [Faster3ck/Converseen#104]
Please, could you add the features of webP to configure in export? (as compression yes/no and compression level).

Thank you

**Comment by Faster3ck** [comment]
Thank you very much for your suggestion, I will add this feature in a future version of the program!

**Comment by Faster3ck** [comment]
The webP features have been added to the latest versions of Converseen, thanks again for the suggestion! :)

**Comment by RafaelLinux** [comment]
I saw it!!! In fact, I downloaded AppImage version to use it, cause Tumbleweed still doesn't have compiled latest version so I must add a big THANKS for let users to have always latest version in AppImage!!!! Thx, thx, thx
