### ISSUE TITLE
Is Converseen still maintained?

### ISSUE THREAD

**Issue by RafaelLinux** [Faster3ck/Converseen#105]
I can see since January issues are not replied. Could it be that (unfortunately) Converseen is not yet maintained?

**Comment by Faster3ck** [comment]
Yes, the project is still maintained. I released the latest version of the program about 1 month ago and I'm currently working on an AppImage and a Snap package that will be released soon! :)

**Comment by RafaelLinux** [comment]
Really interesting. Despite I use openSUSE Tumbleweed and then I have always latest application versions, I always prefer AppImage format when I want to use an application not still updated in my distro repositories.

So thank you for you info and work!!!
