### ISSUE TITLE
Intagrate into a translation service

### ISSUE THREAD

**Issue by libreajans** [Faster3ck/Converseen#106]
Hi, could you add Converseen to a free translation service?

There is plenty of choice for open-source projects.

https://hosted.weblate.org
- "This Weblate instance hosts translations for various libre software projects. Weblate can host your project as well, please get in touch." 

https://crowdin.com/pricing
- "Crowdin for Open Source: We support the open source community. If you're building awesome non-profit projects that could use the power of Crowdin, we're happy to help with this free option. Make your content multilingual to reach a global audience."

https://poeditor.com/kb/open-source-localization
- "Open Source Software Localization: To localize Open Source software with an OSI approved [licence](http://opensource.org/licenses) for free, using the localization management platform POEditor"

Weblate.org has several advantages. It supports machine translations from several sources (Google Translate, Bing, DeepL). It also has a community that translates several open-source projects. 

Thanks.

**Comment by Faster3ck** [comment]
Thank you very much for your suggestion, I was altready taking in consideration the idea of adding Converseen to a free translation service. I will check your links!
