### ISSUE TITLE
PDF import does not work

### ISSUE THREAD

**Issue by kosuodhmwa** [Faster3ck/Converseen#113]
With that file -> https://drive.google.com/file/d/1XS5rzBOeayduhYVfjVTI0o72GwYRqnoG/view

Result: Nothing

![image](https://user-images.githubusercontent.com/24782840/193873211-4d14b50e-cb94-49bf-bd67-f38708251f0d.png)

Why!?

**Comment by kosuodhmwa** [comment]
Ghostscript = Installed

![image](https://user-images.githubusercontent.com/24782840/193873808-91a2c6eb-7c1f-434c-9f46-68d7de979b09.png)


maybe problem is converseen is 32bit and ghostscript is 64 bit?!?
-> https://github.com/Faster3ck/Converseen/issues/112 

???

**Comment by Faster3ck** [comment]
Hi, please remove the 64 bit version of Ghostscript and install the 32 bit one. Let me know if it works!

**Comment by kosuodhmwa** [comment]
Thank you very much for that fast feedback! :-) - will look on it ASAP.

Question: Is there a 64 Bit installer too?
-> https://github.com/Faster3ck/Converseen/issues/112

But that file extension is really really unknown to me...(?)

**Comment by kosuodhmwa** [comment]
![image](https://user-images.githubusercontent.com/24782840/193884266-d2441196-7709-496f-9eec-0cfa5cd26b78.png)

**Comment by kosuodhmwa** [comment]
![image](https://user-images.githubusercontent.com/24782840/193884539-8fbd5f4c-4953-422d-ba49-82bdf04900bb.png)

**Comment by Faster3ck** [comment]
Please, try to use jpg or png as a output file format
![2022-10-04 19_33_03-Converseen](https://user-images.githubusercontent.com/865207/193887605-883fdade-5aec-4a07-a7e6-88c00e289048.png)

**Comment by kosuodhmwa** [comment]
Now i need to set a new file name for ever JPG that was converted from every PDF page...?

And i never saw any target / output direcory option - where can i set it?

**Comment by kosuodhmwa** [comment]
and there is also nothing (jpeg #1 from PDF page #1) in the source folder

![image](https://user-images.githubusercontent.com/24782840/193889421-c7c2a72e-5f70-48d1-ac83-aa77019cad42.png)

**Comment by kosuodhmwa** [comment]
OK... 

![image](https://user-images.githubusercontent.com/24782840/193890552-92b91c88-c1eb-49ef-867a-af24935330ba.png)

**Comment by Faster3ck** [comment]
I suggest you to set an output directory using the left panel and activate the renaming settings in order to auto-rename the output images.

I also suggest you to change the dimension/dpi in order to find the best settings for the converted files.

At the moment the PDF support is on a basic stage, anyway it can work fine in some scenarios!

Here you can find how to activate the auto rename feature:

![2022-10-04 19_45_51-Converseen](https://user-images.githubusercontent.com/865207/193890427-0de66637-a404-4519-a0b9-80d7b42cf408.png)
