### ISSUE TITLE
Overwrite All is ignored in version 0.9.9.8

### ISSUE THREAD

**Issue by jgvenue** [Faster3ck/Converseen#118]
Converseen - version **0.9.9.8**

When attempting to perform batch conversion (1109 jpg files), **_with "Overwrite all" checked_**, and files exist in the output directory produced by a previous conversion batch process, I'm receiving prompt, "The name chosen is identical to the initial one. Do you want to overwrite the original file?".  I'm forced to respond to this prompt for every file being re-processed.  The prompt is not displayed during the initial batch conversion process.  The designated output directory is a sub directory within the directory where the original files are located.

I see a similar issue was submitted and closed in 2021, with the notation "I fixed the problem in Converseen 0.9.9.4".

FYI - thanks for providing this incredibly helpful utility program.

**Comment by Faster3ck** [comment]
Hi,

Thank you very much for reporting me this bug. I'm working on a new release update and I should have fixed the problem. I'm currently testing the new update and I will release it the sooner possibile.

If I'm not wrong, the program is unable to overwrite the existing images only when the "Rename" option in the left panel is enabled so, please try to disable the renaming option (keeping the "Overwrite all" option checked) and let me know if you are able to overwrite the existing images.

**Comment by Faster3ck** [comment]
The problem has been fixed in Converseen 0.9.10.0
