### ISSUE TITLE
Scale by Percentage does not allow decimals

### ISSUE THREAD

**Issue by TheCalibrator** [Faster3ck/Converseen#127]
This sounds stupid probably, but for example if I wanna scale a 4320x7680 to 1440x2560 it's impossible if there are horizontal and vertical images in the mix, at least without separating. For this reason having a decimal allowed in the % option would be beneficial. Just write 33.33% on both and call it a day. This would be a quick time saver feature.

**Comment by Faster3ck** [comment]
Thank you very much for your kind suggestion, I added this feature in [Converseen 0.9.11.1](https://github.com/Faster3ck/Converseen/releases/tag/v0.9.11.1) :)
