### ISSUE TITLE
Scale by Percentage with decimals gives incorrect resolution after conversion.

### ISSUE THREAD

**Issue by TheCalibrator** [Faster3ck/Converseen#128]
Hi, thanks for including this feature but I gotta point out that there's a small issue.

It doesn't matter if there are horizontal + vertical or only one of them in the list, if I write 66.67% it says under the % field that it will be 1440x2560. However, after converting, the images end up being exactly 1447x2573. 

Also very tiny nitpick but is it possible to make the field automatically convert dot into comma? Just a QOL feature for numpad users.

**Comment by Faster3ck** [comment]
Hi, unfortunately, I didn't notice that the ImageMagick library is unable to correctly handle decimal numbers, so I rewrote some parts of the code to allow this. Additionally, I replaced the comma with the dot.

Please let me know if everything is working correctly! :)

**Comment by TheCalibrator** [comment]
Since I'm a total noob and on Linux I'll be waiting for the arch package to update. I will definitely let you know if there's any issues with it when I test it tho.

**Comment by TheCalibrator** [comment]
Installed it through Flatpak and I just tested it. Works like a charm. Thanks a lot!
