### ISSUE TITLE
[Feature] CLI

### ISSUE THREAD

**Issue by Pheggas** [Faster3ck/Converseen#130]
Hello. I'd like to use Converseen as a part of my powershell script but unfortunately, CLI is not supported on Windows versions at least. Would it be possible to add such support? I think it wouldn't be much work. Also, i can help if needed. But i'm not a coder.

**Comment by Faster3ck** [comment]
Hi, the program is not intended to be used as a command line utility (although in the future, I might consider adding some form of command line functionality). Given your use case scenario, I would suggest using ImageMagick.

**Comment by Pheggas** [comment]
> I would suggest using ImageMagick.

Yup, I discovered it recently. Pretty cool app not gonna lie!
