### ISSUE TITLE
Output location 

### ISSUE THREAD

**Issue by Taieri** [Faster3ck/Converseen#131]
This is a good utility and would be better served if it has the ability to set the output file location in settings. Default output (using Debian) is to the root of the users home directory which is a bit annoying as there is no option to change it. 

Also the filename for the converted output would be well served if there was say a  '-converted' added to the end of the filename or similar.  As follows:   picture1234.jpg >>> picture1234-converted.jpg  This is especially important when resizing images as this is probably the most utilised feature.

**Comment by Taieri** [comment]
Hi. I've checked the program again and there is no ability to select the destination folder before conversion. I can open the default output folder after conversion but it defaults output to /home/username/   
FYI: I'm running 0.9.7.2  Debian 10 and KDE.

**Comment by Faster3ck** [comment]
Hi, I rearranged the output section in [Converseen 0.11.0.0](https://github.com/Faster3ck/Converseen/releases/tag/v0.11.0.0). Now it should be easier to change the output folder for converted images!
![converseen-appdata-1_2](https://github.com/Faster3ck/Converseen/assets/865207/325b74ea-2b6a-401a-9deb-8198c4fe9da5)
