### ISSUE TITLE
Port converseen to Qt6

### ISSUE THREAD

**Issue by david-geiger** [Faster3ck/Converseen#140]
Hi,

Have you planned to port converseen to Qt6?

Regards,
David

**Comment by david-geiger** [comment]
Hi,

Any news? or suggestion?

**Comment by Faster3ck** [comment]
Hello and sorry for the late response. Currently, I have not yet planned a porting to Qt6 because I am uncertain about whether it would limit the program's compatibility with older versions of Ubuntu. Anyway, I plan to start the porting process in the next few weeks.

**Comment by Faster3ck** [comment]
Hi, I have really good news about the porting to Qt6. By modifying a few lines of code (fewer than I would have imagined) I managed to make Converseen compile with both Qt5 and Qt6, and as a result the program will be able to compile without any problems even on older versions of Ubuntu.

I will make a new release as soon as possible!

**Comment by Faster3ck** [comment]
Hi, now Converseen can be compiled with both Qt5 and Qt6! You can check the instructions in the [INSTALL.md](https://github.com/Faster3ck/Converseen/blob/main/INSTALL.md) file :)

**Comment by david-geiger** [comment]
Thank you very much :)
