### ISSUE TITLE
DPI bug after latest update

### ISSUE THREAD

**Issue by bungadrum** [Faster3ck/Converseen#141]
I have just updated to the latest 0.11.0.0 portable in Windows 10. By default it is set to 96 dpi when I do a convert process of a batch it always converts it to 300 dpi no matter what I set. I even tried downgrading to the previous portable version before this one and I get same problem it always sets 300 dpi instead of 96 dpi how to fix this?

**Comment by bungadrum** [comment]
It works now after I changed the default locations for the destination folder and where the app was located

**Comment by bungadrum** [comment]
Again same problem came back even tried it on a diffrent PC and it gives me same problem this is how I set it and it still gives me 300 DPI and some times it sets the height by itself even if I don't input anything. Tried it on previous version as well it still puts same DPI not the one set

![Cptr](https://github.com/Faster3ck/Converseen/assets/75974100/00f72e83-0d3b-414b-a862-df98c71b4d3f)

**Comment by Faster3ck** [comment]
I have found a bug regarding the change of resolution. I will release a fix as soon as possible.

**Comment by PenlanV** [comment]
I have a similar issue, the dpi will not change despite what I set it at.  I want to use 300 dpi but it will change form the original dpi, which is 96 dpi.  I have tried saving in different directories and different formats, but it still will not change the dpi, only the px.  I am  using v 0.11.0.1 on Ubuntu 22.10

**Comment by bungadrum** [comment]
I have the oposite problem instead of giving me 96 dpi it gives me the 300 dpi version even if it's default set to 96. Tested the current version both on Linux 22.04 LTS and Windows 10 hope version 12 will fix that bug.

**Comment by Faster3ck** [comment]
Thank you very much for reporting the problem, I'm working to solve the issue with the dpi settings!
