### ISSUE TITLE
Program crashes with no report when I try to import a pdf file

### ISSUE THREAD

**Issue by jbionic2016** [Faster3ck/Converseen#147]
hi there,

I've tried a few different pdfs, but the program keeps shutting itself whenever I import a pdf

Has it been properly tested?

**Comment by jbionic2016** [comment]
@Faster3ck I am using the latest Win-32 version downloadable from sourceforge

**Comment by Faster3ck** [comment]
Ok, thank you!

Before the release, I tested PDF-to-image conversion on a virtual machine and everything seemed to work fine.

Have you checked whether 32-bit Ghostscript is installed on your system? Are you converting the PDF to a common format like jpg or png?

Please, refer to this guide carefully and let me know if the problem persists: https://converseen.fasterland.net/convert-a-pdf-into-images-with-converseen/

**Comment by jbionic2016** [comment]
@Faster3ck Thanks. The problem indeed must have been due to not having GhostScript x32 installed (I had GS x64).
Once I installed the x32 everything seems to work just fine.
In fact, other issue that I had with the output folder not saving the default path miraculously has been resolved too.

Thanks again and best regards.

**Comment by Faster3ck** [comment]
For some reason, the 32-bit version is required, which can be confusing. Anyway, I'm glad the problem is now solved! :)

Greetings,
Francesco
