### ISSUE TITLE
openSUSE version not maintained

### ISSUE THREAD

**Issue by RafaelLinux** [Faster3ck/Converseen#148]
Unfortunately, the version for openSUSE (specifically Tumbleweed, which is supposed to always have the latest version available) is no longer compiled by anyone and is at version 0.9.11.1 so I think you should remove the link to that version from your page and recommend the AppImage version (which is the one I use when I realised how outdated the RPM version is).

Thanks

**Comment by Faster3ck** [comment]
Hello and thank you very much for reporting the problem. I hope package maintenance will be resumed soon. If it doesn't get updated soon, I will try to contact the maintainers because openSUSE is one of the major distributions, and it would be sad if support were dropped!

**Comment by RafaelLinux** [comment]
Thanks to you for take it into account and for your great job!!!
