### ISSUE TITLE
Converseen flatpak icon missing

### ISSUE THREAD

**Issue by illtellyoulater** [Faster3ck/Converseen#151]
I'm running the flatpak version and the program icon is missing.

I also checked that with flatseal, as you can see in the following screenshot.

![Schermata del 2023-11-08 00-19-28](https://github.com/Faster3ck/Converseen/assets/3078931/2f62e5a9-bcb7-4e45-8e94-516423ae1701)

In case it helps, I'm running Pop!_OS 22.04 & GNOME 42.5.

**Comment by Faster3ck** [comment]
Thanks a lot for letting me know about the issue. I'll take a look and fix it!

**Comment by Faster3ck** [comment]
Hi, now the icon should be visible. I tried it on a virtual machine with Pop!_OS and it seems to work correctly.

Perhaps there was a naming problem with the icon which I corrected a few days ago within the Flatpak manifest json!

**Comment by illtellyoulater** [comment]
I confirm it's working now! Thank you! And nice work on the new icon too! 😉👍
