### ISSUE TITLE
Add a hotkey option for closing

### ISSUE THREAD

**Issue by bungadrum** [Faster3ck/Converseen#163]
Is it possible to add a hotkey for closing the app in Linux. On Windows it's ALT-F4, but can you also add a CTRL-Q or CTRL-W option for the Flatpak and Appimage.

**Comment by Faster3ck** [comment]
Thank you very much for the suggestion. I will add the hotkey as soon as possible!

**Comment by Faster3ck** [comment]
I added the CTRL-Q hotkey for closing the app in [Version 0.12.2.2](https://github.com/Faster3ck/Converseen/releases/tag/v0.12.2.2) :)
