### ISSUE TITLE
Language Selection Bug on Snap Install (Linux)

### ISSUE THREAD

**Issue by romulo-godoi** [Faster3ck/Converseen#176]
Hello, 

I'd like to report an issue occurring on Ubuntu 24.04 LTS with version 0.12.2.3 of the application installed via the Snap store. The app defaults to English and does not offer the option to change the language, as shown in the attached screenshot—English is the only available language. This seems to be a bug, as the application is known to be translated into multiple languages. Ideally, it should detect the system language during the installation or at least allow users to manually switch languages in the settings, but only English appears as an option. 

Thank you for looking into this!
![Captura de tela de 2024-10-15 23-56-51](https://github.com/user-attachments/assets/b62f306d-f91e-44df-b06b-07bbcb9e7566)

**Comment by Faster3ck** [comment]
Hi,

Thank you for reporting the bug. I can confirm that, for some reason, the application is no longer able to access the location files. It’s likely that something has changed in the Snap folder structure.

I’ll work on finding a solution as soon as possible!

**Comment by Faster3ck** [comment]
The bug affecting Snap package localization has been fixed in [Converseen 0.12.2.4](https://github.com/Faster3ck/Converseen/releases/tag/v0.12.2.4). 
Thank you again for reporting the issue! :)

**Comment by romulo-godoi** [comment]
> The bug affecting Snap package localization has been fixed in [Converseen 0.12.2.4](https://github.com/Faster3ck/Converseen/releases/tag/v0.12.2.4). Thank you again for reporting the issue! :)

Thanks. Just got the update. Everything working now.
