### ISSUE TITLE
Feature request: preserve EXIF orientation metadata

### ISSUE THREAD

**Issue by cuceda** [Faster3ck/Converseen#179]
Hi,

There is an image which does not resize well. It is a JPEG wallpaper which originally makes 4024x6048 px. When I scale down to 3840x2160 px I get the opposite: 2160x3840. The "Maintain aspect ratio" is left unchecked. No additional actions are set.

All other pictures I have tested so far do not trigger this issue.

**Comment by cuceda** [comment]
GIMP gave me a hint about the reasonable cause of this issue:
![image](https://github.com/user-attachments/assets/a2985829-beb8-4655-94ff-389d769bd60a)

I didn't know this EXIF metadata existed at all. I will update the title of this issue.

**Comment by Faster3ck** [comment]
Hi, and thank you very much for reporting this issue.
I haven't received reports about this problem before, so I believe it might be a special case where certain EXIF metadata causes conflicts with the correct orientation of the image.

The program should currently read and preserve metadata.

Have you tried checking or unchecking the “Image Settings” -> “Remove image metadata” option to see if it changes the result?

Additionally, would it be possible for you to share the image that causes this issue so I can analyze the problem further?

**Comment by cuceda** [comment]
Hi, I've checked that and it turns out that I had enabled that option but didn't remember. If I don't remove image metadata the converted image preservers the aspect ratio. So I guess there's no bug nor feature request.

This was the image: https://media.defense.gov/2024/Aug/23/2003533703/-1/-1/0/240815-F-YI652-1501.JPG

Thank you and congrats for the app. It really handful.

**Comment by Faster3ck** [comment]
Perfect! I'm glad the problem has been solved! :)

Greetings,
Francesco
