### ISSUE TITLE
App runtime update message

### ISSUE THREAD

**Issue by bungadrum** [Faster3ck/Converseen#180]
In the latest Flatpak version whenever I run a update in the terminal it gives me this message:

"Info: org.kde.Platrofm//6.6 is end-of-life, with reason: We strongly recommend moving to the latest stable version of the Platform and SDK
Applications using the runtime:
net.fasterland.converseen"

**Comment by Faster3ck** [comment]
Hi, and thank you very much for reporting the problem.
I have upgraded the Flatpak to the latest version of the KDE Framework, and everything should now work without any issues.

The updated package should already be available for download! :)

Greetings,
Francesco
