### ISSUE TITLE
Adding a Toggle button for a simple dark mode for Windows

### ISSUE THREAD

**Issue by bungadrum** [Faster3ck/Converseen#181]
On the Flatpak everything works perfectly, but would it be possible to add a dark mode toggle button for the installable and portable version in Windows? Or adding some kinda option in Choose color to replace the white/grey default since it can't follow the system theme like in Linux

**Comment by Faster3ck** [comment]
Hi, unfortunately, due to compatibility issues with older versions of Windows, Converseen still relies on Qt5, which does not natively support dark mode.

However, a Qt6-based version is coming soon and will offer full dark mode support on Windows without any issues!
