### ISSUE TITLE
file converseen_import.desktop not in Plasma5 directory

### ISSUE THREAD

**Issue by david-geiger** [Faster3ck/Converseen#30]
Hi,

I think it would be preferable to install "converseen_import.desktop" file in the Plasma5 directory and no more in the KDE4's one, something like that:

diff -Nru a/CMakeLists.txt b/CMakeLists.txt
-install(FILES res/converseen_import.desktop DESTINATION ${CMAKE_INSTALL_PREFIX}/share/kde4/services/ServiceMenus)
+install(FILES res/converseen_import.desktop DESTINATION ${CMAKE_INSTALL_PREFIX}/share/kservices5/ServiceMenus)

WDYT?

Regards,
David

**Comment by Faster3ck** [comment]
Thank you very much for the tip. I forgot to replace the old kde4 directory with the Plasma5 one.
