### ISSUE TITLE
Magick libs are found, but variables are not set

### ISSUE THREAD

**Issue by nick87720z** [Faster3ck/Converseen#44]
Trying to configure latest converseen, i get following output.
```-- Detecting CXX compile features - done
-- Found ImageMagick: /usr/bin/convert (found version "7.0.7-8") 
-- Could NOT find ImageMagick (missing:  ImageMagick_Magick++_LIBRARY) (found version "7.0.7-8")
-- Could NOT find ImageMagick (missing:  ImageMagick_MagickWand_LIBRARY) (found version "7.0.7-8")
-- Could NOT find ImageMagick (missing:  ImageMagick_MagickCore_LIBRARY) (found version "7.0.7-8")
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ImageMagick_Magick++_LIBRARY
    linked by target "converseen" in directory /home/nick87720z/dist/Converseen
ImageMagick_MagickCore_LIBRARY
    linked by target "converseen" in directory /home/nick87720z/dist/Converseen

-- Configuring incomplete, errors occurred!
```

It happens both with release and git sources. Doing ccmake, i found only these Magick vars set:
ImageMagick_EXECUTABLE_DIR : /usr/bin
ImageMagick_Magick++_INCLUDE_DIR : /usr/include/ImageMagick-7

However, runing pkg-config from terminal, i have all output ok for --cflags and --libs. Also can run --cflags-inly-I to get those INCLUDE_DIR values, but have no idea, what to assign for ARCH_INCLUDE_DIR.

**Comment by Faster3ck** [comment]
Hi,

What Linux distro are you using? Have you installed the ImageMagick devel libraries?
I would suggest you to install the Converseen package from the repository of your distro if it's available.

**Comment by nick87720z** [comment]
destro - gentoo. Converseen version is in log (latest both git and release are claimed to have its support).

And as i wrote, i ran pkg-config from terminal, getting all flags with --libs and --cflags for all 3 libs.
Btw, the -I flag is same for all 3 required Magick parts (++, core, wand).

I'm currently writing ebuild for new version. Previous was 0.9.5.2, without such problems, but it was with IM 6.x, now i have 7.x, and that version fails to build, what was reason for ebuild's version bump.

Version from distro is very old - 0.6.8-r1. Also i moved to IM 7.x due to GLSA warning about security problems. Once new converseen ebuild is wrorking, i will probably send it for version bump. If anyone else will not do it earlier.

**Comment by nick87720z** [comment]
Tested manual config via ccmake: filled related *_INCLUDE_DIR with "/usr/include/ImageMagick-7"
and *_LIBRARY with **pkg-config --libs** output for each. **Built without futher troubles.**
_ARCH_INCLUDE_DIR's were not required._

**Comment by nick87720z** [comment]
Next problem, making it impossible, to configure properly without ccmake:
This command:
`$ cmake -DImageMagick_Magick++_LIBRARY="$( pkg-config --libs Magick++ )" -DImageMagick_MagickCore_INCLUDE_DIR="$( pkg-config --cflags-only-I MagickCore )" -DImageMagick_MagickCore_LIBRARY="$( pkg-config --libs MagickCore )" -DImageMagick_MagickWand_INCLUDE_DIR="$( pkg-config --cflags-only-I MagickWand )" -DImageMagick_MagickWand_LIBRARY="$( pkg-config --libs MagickWand )" ..`

Results into following log at the end:
```-- Found ImageMagick: /usr/bin/convert (found version "7.0.7-8") 
-- Found ImageMagick: /home/nick87720z/dist/converseen-0.9.6.2/build/-lMagick++-7.Q16HDRI -lMagickWand-7.Q16HDRI -lMagickCore-7.Q16HDRI (found version "7.0.7-8") 
-- Found ImageMagick: /home/nick87720z/dist/converseen-0.9.6.2/build/-lMagickWand-7.Q16HDRI -lMagickCore-7.Q16HDRI (found version "7.0.7-8") 
-- Found ImageMagick: /home/nick87720z/dist/converseen-0.9.6.2/build/-lMagickCore-7.Q16HDRI (found version "7.0.7-8")
```
i.e., by some reason it modifies specified parameters, prepending builddir (from which i ran cmake) to all these arguments. Though it doesn't print *_INCLUDE props, specified in command line, they are affected in same way.

As for property ImageMagick_Magick++_INCLUDE_DIR: it is autodetected, and is not affected by build dir prepending.

So, the only possible way for current particular release is to use ccmake - no ebuilds or other automatic means (in case of portage it is possible, though to fix siuation manually, if possible, then continue emerging, but it is ugly hack)

**Comment by nick87720z** [comment]
Final working cmake args:
```
mycmakeargs=(
    -DImageMagick_Magick++_LIBRARY="$(pkg-config --variable=libdir Magick++)/lib$(pkg-config --variable=libname Magick++).so"
    -DImageMagick_MagickCore_INCLUDE_DIR="$( pkg-config --cflags-only-I MagickCore | tail -c+3 )"
    -DImageMagick_MagickCore_LIBRARY="$(pkg-config --variable=libdir MagickCore)/lib$(pkg-config --variable=libname MagickCore).so"
    -DImageMagick_MagickWand_INCLUDE_DIR="$( pkg-config --cflags-only-I MagickWand | tail -c+3 )"
    -DImageMagick_MagickWand_LIBRARY="$(pkg-config --variable=libdir MagickWand)/lib$(pkg-config --variable=libname MagickWand).so"
    )
```

**Comment by Faster3ck** [comment]
Sorry for the late response and thank you very much for your help. It could be useful.
Anyway I managed to compile successfully Converseen on Arch Linux with ImageMagick 7.0.7 (the version on the repo) using the original cmake file and it worked perfectly with no modifications, so at the moment I can't say the reason why cmake failed to compile Converseen on your system.

**Comment by littlebugyang** [comment]
> Final working cmake args:
> 
> ```
> mycmakeargs=(
>     -DImageMagick_Magick++_LIBRARY="$(pkg-config --variable=libdir Magick++)/lib$(pkg-config --variable=libname Magick++).so"
>     -DImageMagick_MagickCore_INCLUDE_DIR="$( pkg-config --cflags-only-I MagickCore | tail -c+3 )"
>     -DImageMagick_MagickCore_LIBRARY="$(pkg-config --variable=libdir MagickCore)/lib$(pkg-config --variable=libname MagickCore).so"
>     -DImageMagick_MagickWand_INCLUDE_DIR="$( pkg-config --cflags-only-I MagickWand | tail -c+3 )"
>     -DImageMagick_MagickWand_LIBRARY="$(pkg-config --variable=libdir MagickWand)/lib$(pkg-config --variable=libname MagickWand).so"
>     )
> ```
> 
> Btw, pkg-config is claimed to suppot windows as well as osx and linux, so you could try get it working via cmake.

Your solution really helps me a lot.
