### ISSUE TITLE
Option for cleanup image metagata (EXIF, sRGB, etc)

### ISSUE THREAD

**Issue by MurzNN** [Faster3ck/Converseen#53]
ImageMagick have `-strip` option that cleanup images from metadata records:

> strip the image of any profiles, comments or these PNG chunks: bKGD,cHRM,EXIF,gAMA,iCCP,iTXt,sRGB,tEXt,zCCP,zTXt,date.

Will be good to have same option available in Converseen!

**Comment by Faster3ck** [comment]
This feature has been added in Converseen 0.9.10.0, thanks again for the suggestion!
