### ISSUE TITLE
Development of Converseen discontinued?

### ISSUE THREAD

**Issue by vlrmt** [Faster3ck/Converseen#55]
Hi Francesco,
the fact that Converseen has not been updated for 1 year and 4 months sounds like bad news for the future of your software...
Is this a definitive end?
I had a few issues and suggestions to share, but if they are to _not_ be taken in account, then no need to waste my time writing about them :)
Cheers.
PS: I'm creating this issue since it's impossible to contact you via http://converseen.fasterland.net/contact-me/ ("There was an error trying to send your message. Please try again later.").

**Comment by Faster3ck** [comment]
Hi,

I just released a new update of Converseen. :) 

The project is still alive but unfortunately, at the moment, I'm very busy so I have little time to work on Converseen.

I'm currently working on Converseen 1.0, a project written from scratch on which I hope to add all the new features the program deserves. For this reason I stopped to add new features on the 0.x version of the program even if I always work on bugfixes, but I'm taking account of all the kind suggestions made by the users.
Unfortunately Converseen 1.0 is not finished and I don't know when I will finish it. :(

Anyway, if you want to share your suggestions with me, feel free to use the contact form on the website (it should now work) or contact me via email, you can find my address in the information dialog of Converseen. Any kind of suggestion could be helpful for the development of the program. :)

**Comment by SlashTray** [comment]
Good news!
Thank you for the latest update (0.9.7), proposed for installation today via ppa:ubuntuhandbook1/apps

One of the issues I had detected was the default PNG compression level, set to 7 (out of 100!) when I first installed version 0.9.2-1build1 coming from the Ubuntu repo (that was before adding the PPA mentioned above). The outcome being that the output image was about 10 times heavier than the original image after a simple flip operation ;)
I modified the PNG compression level to 85 (same value as the default for JPG) to fix this issue.

I'll stick to this sole issue here, so you can close it if - or when - this very issue is fixed.
