### ISSUE TITLE
All errors

### ISSUE THREAD

**Issue by jasonbrown1965** [Faster3ck/Converseen#64]
Installed Converseen to Zorin OS, attempted to convert 102 RAW images from a Canon SLR.

0% conversion, no error codes immediately apparent, just "error".

No biggie, just so ya know!

**Comment by Faster3ck** [comment]
Hi,

In order to convert RAW formats on Linux using Converseen you may need to install dcraw. :)

**Comment by PolarFox** [comment]
Who is doing the packaging? Maybe dcraw should be a dependency?
