### ISSUE TITLE
Converting to PDF fails

### ISSUE THREAD

**Issue by MarHaj** [Faster3ck/Converseen#69]
Doesn't convert at all to `pdf` from `jpg` and `png` images at the least.

```
Conversion status report:
Total: 1
Converted: 0
Error:0
```

Running Converseen 0.9.7 installed from repository ppa:ubuntuhandbook1/apps on Linux Mint 19.2.

Maybe some prerequisites/libraries missing?

**Comment by Faster3ck** [comment]
Hello,

Please, try to install the ghostscript package. ImageMagick may require it in order to process PDF files.

**Comment by MarHaj** [comment]
@Faster3ck:
> Please, try to install the ghostscript package. ImageMagick may require it in order to process PDF files.

I had ghostscript 9.26 installed (verified bin is in the path).  And seems imagemagic too:

ii  imagemagick   8:6.9.7.4+dfsg-16ubuntu6.8    amd64    image manipulation programs -- binaries
ii  imagemagick-6-common   8:6.9.7.4+dfsg-16ubuntu6.8   all   image manipulation programs -- infrastructure
ii  imagemagick-6.q16   8:6.9.7.4+dfsg-16ubuntu6.8   amd64  image manipulation programs -- quantum depth Q16

**Comment by MarHaj** [comment]
I've found the problem and the solution:

There is a ImageMagic policy file `/etc/ImageMagick-6/policy.xml`. There I had a line disabling ghostscript from reading/writing pdf files: `<policy domain="coder" rights="none" pattern="PDF" />`. I changed it to `<policy domain="coder" rights="read|write" pattern="PDF" />` and the problem "converting to pdf fails" does not exit anymore.
