### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by binyominzeev** [Faster3ck/Converseen#75]
I was converting from PNG to JPEG multiple files when I got the following error message:

`Error: converseen: unable to open file '/tmp/magick-16632mmi0C1U8cmJK': No such file or directory @ error/constitute.c/ReadImage/544`

![Screenshot_2020-06-11_13-23-39](https://user-images.githubusercontent.com/4866177/84379920-defa6100-abe6-11ea-878c-a349a74bce61.png)

I also tried to convert a different group of PNGs, seemingly similar, and then it worked. But on these files it stopped working.

**Comment by Faster3ck** [comment]
Hi,

Please, check if libjpeg and libpng are installed on your system. Moreover, check if all the dependencies requested by ImageMagick are correctly installed.

**Comment by binyominzeev** [comment]
Libjpeg and libpng are installed, as follows:

```
bz@bz-HP-Laptop-15-bs1xx:~$ apt list --installed | grep libjp

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libjpeg-dev/bionic,now 8c-2ubuntu8 amd64 [installed,automatic]
libjpeg-turbo8/bionic-updates,bionic-security,now 1.5.2-0ubuntu5.18.04.4 amd64 [installed]
libjpeg-turbo8-dev/bionic-updates,bionic-security,now 1.5.2-0ubuntu5.18.04.4 amd64 [installed,automatic]
libjpeg8/bionic,now 8c-2ubuntu8 amd64 [installed]
libjpeg8-dev/bionic,now 8c-2ubuntu8 amd64 [installed,automatic]
bz@bz-HP-Laptop-15-bs1xx:~$ apt list --installed | grep libpng

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libpng-dev/bionic-updates,bionic-security,now 1.6.34-1ubuntu0.18.04.2 amd64 [installed,automatic]
libpng-tools/bionic-updates,bionic-security,now 1.6.34-1ubuntu0.18.04.2 amd64 [installed,automatic]
libpng16-16/bionic-updates,bionic-security,now 1.6.34-1ubuntu0.18.04.2 amd64 [installed]
```

I am not sure what do you mean by "dependencies requested by ImageMagick". I have the version downloaded from official website, where it says: "Complete portable application on Linux, no installation required. Just download and run."

https://imagemagick.org/script/download.php

**Comment by Faster3ck** [comment]
I'm not sure if Converseen can run properly with the downloaded version of ImageMagick. I would suggest you to download ImageMagick from the ubuntu official repositories and try to convert your images again.

I also suggest you to run the command `identify image.png` to check if the image you are trying to convert is ok. Sometimes ImageMagick is unable to convert corrupted images even if some other tools are able to open them.

**Comment by binyominzeev** [comment]
Thank you, great! "Identify" did the trick and provided with the correct error message I needed to proceed. I needed to install the webp library, found out after the following error message:

```
:~/Pictures$ identify 26.png 
identify-im6.q16: delegate failed `'dwebp' -pam '%i' -o '%o'' @ error/delegate.c/InvokeDelegate/1919.
identify-im6.q16: unable to open file `/tmp/magick-4196Mo17yw9XlD6i': No such file or directory @ error/constitute.c/ReadImage/544.
```
