### ISSUE TITLE
not able to launch in manjaro cinnamon 20.1

### ISSUE THREAD

**Issue by anwaruddin2k** [Faster3ck/Converseen#78]
unable to launch convserseen 0.9.8.1-1 in manjaro 

older version wordked fine

**Comment by anwaruddin2k** [comment]
![Screenshot from 2020-09-20 00-19-25](https://user-images.githubusercontent.com/53415502/93686899-03fc4b00-fad7-11ea-81a5-e8fffa142e92.png)
![Screenshot from 2020-09-20 00-19-00](https://user-images.githubusercontent.com/53415502/93686900-05c60e80-fad7-11ea-846c-5a118d42a611.png)
![Screenshot from 2020-09-20 00-18-31](https://user-images.githubusercontent.com/53415502/93686901-078fd200-fad7-11ea-943b-5c9ac6bf8deb.png)
![Screenshot from 2020-09-20 00-17-58](https://user-images.githubusercontent.com/53415502/93686903-078fd200-fad7-11ea-863e-fb21ac226efc.png)

**Comment by Faster3ck** [comment]
Hi,

Please update your system, run converseen from command line and let me know if you get an error message
