### ISSUE TITLE
Open destination n'est pas actif après conversion

### ISSUE THREAD

**Issue by alain230** [Faster3ck/Converseen#79]
Bonjour,
Je viens de passer à Ubuntu 18.4 et j'ai installé Converseen ( que j'utilise depuis longtemps )
Je viens de constater que la conversion se fait bien mais  " Open destination" n'est pas actif et je ne retrouve pas la conversion dans ma destination ( Save In ).
Pouvez-vous me dépanner.
Merci
Alain

**Comment by Faster3ck** [comment]
Hi,

Please, check this discussion to solve the issue:
https://github.com/Faster3ck/Converseen/issues/74#issuecomment-718766770
