### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by Denisov21** [Faster3ck/Converseen#82]
Hi, is it possible to translate the following window?
![image](https://user-images.githubusercontent.com/2547815/101244712-52011200-3708-11eb-9285-cc4d16e5f644.png)

**Comment by Faster3ck** [comment]
I checked the documentation and it is possible to get these dialogs translated automatically. I will add the fix in the new release of the program! :)

**Comment by Faster3ck** [comment]
I fixed the problem in Converseen 0.9.9.0. Feel free to update the program to the latest version! :)
