### ISSUE TITLE
Wrong path for .converseen.conf

### ISSUE THREAD

**Issue by SameExpert** [Faster3ck/Converseen#88]
According to [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html), configuration files have to be in **$XDG_CONFIG_HOME** but currently Converseen is using **$XDG_DATA_HOME** for config.

**Comment by Faster3ck** [comment]
Thank you very much for your kind suggestion, I will change the configuration directory with the next minor release of the program!

**Comment by Faster3ck** [comment]
I fixed the configuration directory in version 0.9.9.1, thanks again!
