### ISSUE TITLE
No JFIF support.

### ISSUE THREAD

**Issue by ezxpro** [Faster3ck/Converseen#89]
I was trying to convert some files today, and despite Converseen's vast amount of supported formats, I was surprised to see it doesn't support JFIF.

Are there any plans to implement this somewhere in the future?

But regardless of that, the software is already impressive, thanks for the work man.

**Comment by Faster3ck** [comment]
Hi, 

Thank you for reporting this issue. Actually, the JFIF format is supported by ImageMagick but for some reason it is not shown in the list of the readable/writable formats.

Anyway, I added manually the format in the version 0.9.9.1
