### ISSUE TITLE
Traditional Chinese language files cannot be selected and used normally

### ISSUE THREAD

**Issue by wcxu21** [Faster3ck/Converseen#91]
Hi
I come from China.
I found that the Chinese language provided in the application cannot be selected and displayed in the settings. This may be an error of the application. I hope you can fix it.
Test OS: Windows 7, Windows 10

**Comment by Faster3ck** [comment]
Hello,

Unfortunately at the moment the Chinese language isn't available for the application. The files into the "translations" folder are generic translation files for some components of the graphical interface. The actual translation files are the ones stored into the "loc" folder.

I hope to find someone able to translate the application in Chinese soon! :)
