### ISSUE TITLE
Feature Request Converseen for macOS

### ISSUE THREAD

**Issue by dtantono** [Faster3ck/Converseen#93]
Hi
Is it possible for this available on macOS?

**Comment by Faster3ck** [comment]
Yes, probabily Converseen will be ported to macOS in the nex weeks!

**Comment by Faster3ck** [comment]
Hi, Converseen is finally available for macOS too. I made a beta release for testing and it's possible to download it here: https://github.com/Faster3ck/Converseen/releases/tag/v0.10.0.1
